update skfde runtime hook

diff --git a/src/hooks/skfde b/src/hooks/skfde
--- a/src/hooks/skfde
+++ b/src/hooks/skfde
@@ -2,39 +2,60 @@
 
 
 SKFDE_CONFIG_FILE="/etc/skfde.conf"
-SKFDE_LUKS_DEV=""
-SKFDE_LUKS_NAME=""
-SKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP=""
-FIDO2LUKS_SALT=""
-FIDO2LUKS_CREDENTIAL_ID=""
-
+SKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP="5"
+SKFDE_CRYPTSETUP_RETRY="3"
 
 message() {
   echo "$@" >&2
   return 0
 }
 
+skfde_open() {
+  message "Generate the solokey response"
+  _skfde_response="$(fido2luks print-secret --pin)"
+  message "Received Response: '$_skfde_response'"
+
+  message "Passing '$_skfde_response' to cryptsetup"
+  _tmp="$(printf %s "$_skfde_response" | cryptsetup luksOpen "$SKFDE_LUKS_DEV" "$SKFDE_LUKS_NAME" 2>&1)"
+  _rc=$?
+
+ if [ "$_rc" -eq 0 ]; then
+   message "Decryption was successful."
+   sleep "$SKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
+   return 0
+ else
+   message "FAILED! [$_rc] $_tmp"
+   return 1
+ fi
+}
+
 run_hook() {
 
+  # load variables from conf file
   . "$SKFDE_CONFIG_FILE" || {
     message "Failed to read the SKFDE configuration file '$SKFDE_CONFIG_FILE'"
     return 1
   }
 
-  message " Generate the solokey response"
-  _skfde_response="$(fido2luks print-secret --pin)"
-  message " Received Response: '$_skfde_response'"
+  # sanity check
+  if [ -z "$SKFDE_LUKS_DEV" ]; then
+    message "Please check SKFDE_LUKS_DEV in $SKFDE_CONFIG_FILE"
+  elif [ -z "$SKFDE_CHALLENGE" ] || [ -z "$SKFDE_CREDENTIAL" ]; then
+    message "Please set SoloKey challenge & credential in $SKFDE_CONFIG_FILE"
+  fi
 
-  message " Passing '$_skfde_response' to cryptsetup"
-  _tmp="$(printf %s "$_skfde_response" | cryptsetup luksOpen "$SKFDE_LUKS_DEV" "$SKFDE_LUKS_NAME" 2>&1)"
-  _rc=$?
+  # add dm-crypt kernel module
+  modprobe -a -q dm-crypt
 
- if [ "$_rc" -eq 0 ]; then
-   message " Decryption was successful."
-   sleep "$SKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
-   return 0
- else
-   message " FAILED! [$_rc] $_tmp"
-   return 1
- fi
+  # configure retry
+  local retry
+  retry=1
+  while [ "$retry" -le "$SKFDE_CRYPTSETUP_RETRY" ]; do
+    message "Attempt $retry :"
+    skfde_open && return 0
+    retry=$((retry+1))
+  done
+
+  message "Decryption Failed"
+  return 1
 }
