fix the config file option

diff --git a/src/skfde-open b/src/skfde-open
--- a/src/skfde-open
+++ b/src/skfde-open
@@ -10,28 +10,36 @@ SKFDE_RESPONSE=""
 SKFDE_PASSPHRASE=""
 SKFDE_TEST_PASSPHRASE=""
 
+if [ -r "$SKFDE_CONFIG_FILE" ]; then
+  . "$SKFDE_CONFIG_FILE"
+else
+  echo "Failed to read the deafult SKFDE configuration file '$SKFDE_CONFIG_FILE'"
+  exit 1
+fi
+
 while getopts ":d:s:n:c:th" opt; do
   case "$opt" in
-    d)
-      SKFDE_LUKS_DEV="$OPTARG"
-      printf '%s\n' "INFO: Setting device to '$OPTARG'."
-      ;;
     c)
       SKFDE_CONFIG_FILE="$OPTARG"
-      printf '%s\n' "INFO: Setting config file to '$OPTARG'."
+      printf '%s\n' "INFO: Setting config file to '$SKFDE_CONFIG_FILE'."
+        . "$SKFDE_CONFIG_FILE"
+      ;;
+    d)
+      SKFDE_LUKS_DEV="$OPTARG"
+      printf '%s\n' "INFO: Setting device to '$SKFDE_LUKS_DEV'."
       ;;
     s)
       if [ "$OPTARG" -gt -8 ] && [ "$OPTARG" -lt 8 ]; then
         SKFDE_LUKS_KEYSLOT="$OPTARG"
-        printf '%s\n' "INFO: Setting LUKS keyslot to '$OPTARG'."
+        printf '%s\n' "INFO: Setting LUKS keyslot to '$SKFDE_LUKS_KEYSLOT'."
       else
-        printf '%s\n' "ERROR: Chosen LUKS keyslot '$OPTARG' is invalid. Please choose valid LUKS keyslot number between '0-7'."
+        printf '%s\n' "ERROR: Chosen LUKS keyslot '$SKFDE_LUKS_KEYSLOT' is invalid. Please choose valid LUKS keyslot number between '0-7'."
         exit 1
       fi
       ;;
     n)
       SKFDE_LUKS_NAME="$OPTARG"
-      printf '%s\n' "INFO: Setting name to '$OPTARG'."
+      printf '%s\n' "INFO: Setting name to '$SKFDE_LUKS_NAME'."
       ;;
     t)
       SKFDE_TEST_PASSPHRASE="--test-passphrase"
@@ -60,13 +68,6 @@ while getopts ":d:s:n:c:th" opt; do
       ;;
   esac
 done
-
-if [ -r "$SKFDE_CONFIG_FILE" ]; then
-  . "$SKFDE_CONFIG_FILE"
-else
-  echo "Failed to read the SKFDE configuration file '$SKFDE_CONFIG_FILE'"
-  exit 1
-fi
 
 if [ -z "$SKFDE_LUKS_DEV" ]; then
   echo "ERROR: Device not selected. Please select an existing device using '-d' option."
